python3 sje_train.py \
    --seed 123 \
    --use_gpu True \
    --dataset birds \
    --model_type icml \
    --data_dir data/cvpr2016_cub \
    --train_split trainval \
    --learning_rate 0.0007 \
    --symmetric True \
    --epochs 200 \
    --checkpoint_dir ckpt \
    --save_file sje_cub_c10_hybrid
